#!/usr/bin/env sh
cat <<EOF

  ██          ██   ██        ██
 ░░          ░░   ░██       ░██
  ██ ███████  ██ ██████     ░██  █████  ██    ██
 ░██░░██░░░██░██░░░██░   ██████ ██░░░██░██   ░██
 ░██ ░██  ░██░██  ░██   ██░░░██░███████░░██ ░██
 ░██ ░██  ░██░██  ░██  ░██  ░██░██░░░░  ░░████
 ░██ ███  ░██░██  ░░██ ░░██████░░██████  ░░██
 ░░ ░░░   ░░ ░░    ░░   ░░░░░░  ░░░░░░    ░░

 v0.2

 T0mab 2K16 DIP FTW !!!!!!

EOF

# Fancy things

NORMAL= GREEN= YELLOW= RED=

test -t 1 && {
    NORMAL=$(tput sgr0)
    GREEN=$(tput setaf 2; tput bold)
    YELLOW=$(tput setaf 3)
    RED=$(tput setaf 1)
}

warn () {
    local _r=$?
    echo "$RED $* $NORMAL" >&2
    return $_r
}

die () {
    warn "$*"
    exit
}

read_p () { # backward compatible equivalent of the bash read -p (prompt)
    echo $1
    read $2
}

[ -z ${VIRTUAL_ENV+x} ] &&
    die "Virtualenv not activated please activate it first !"

# Vars {{{
CURRENT_PATH="$(pwd)"
APP_NAME=$(basename $VIRTUAL_ENV)
SETTINGS_PATH="$CURRENT_PATH/$APP_NAME/settings/dev.py"

#  }}}

# Functions {{{
editVenvPostScripts() {
    read_p "Would you like to edit venv scripts ? $YELLOW [y/n] $NORMAL : " ANSWER
    case $ANSWER in
            [yY]* )
                [ -z ${EDITOR+x} ] && {
                    echo "Please set $RED EDITOR $NORMAL env var before trying to edit files!"
                    exit
                }
                $EDITOR $VIRTUAL_ENV/bin/postactivate $VIRTUAL_ENV/bin/postdeactivate;;
            [nN]* )
               exit;;
            * )
               echo "Enter y or n please";;
    esac
}

addVenvPostScripts() {
    echo "export $1=$2" >> $VIRTUAL_ENV/bin/postactivate
    echo "unset $1" >> $VIRTUAL_ENV/bin/postdeactivate
}

getVenvDevSettingsPath() {
    unset SETTINGS_PATH
    read_p "Please provide fullpath to settings/dev.py ex : $GREEN $CURRENT_PATH/$APP_NAME/settings/dev.settings.py $NORMAL: " SETTINGS_PATH

    if [ -z ${SETTINGS_PATH} ];then
        echo "$RED"
        echo "Process cancelled $NORMAL"
        exit 1
    fi
}

getSettings() {
    SETTINGS=(DJANGO_SETTINGS_MODULE=$APP_NAME.settings.dev)
    SETTINGS+=($(sed -nr "s/.*environ.get\('([^']+)', *['\"]([^'\"]+).*/\1=\2/p" $1))
}

processSettings() {
    for SETTING in "${SETTINGS[@]}";
    do
        read_p "put $GREEN'$SETTING'$NORMAL value in postactivate ? $YELLOW [y/n] $NORMAL : " ANSWER

        case $ANSWER in
            [yY]* )
                putSetting $SETTING;;
            [nN]* )
                ;;
            * )
                echo "Enter y or n please";;
        esac
    done
}

putSetting() {
    IFS== read key value <<< $1
    addVenvPostScripts $key $value
}

# }}}

# Main stuff
while true
do
  read_p "App settings path : $GREEN $SETTINGS_PATH $NORMAL correct ? $YELLOW [y/n] $NORMAL : " ANSWER
  case $ANSWER in
   [yY]* )
           getSettings $SETTINGS_PATH
           break;;

   [nN]* )
           getVenvDevSettingsPath
           getSettings $SETTINGS_PATH
           break;;

   * )     echo "Enter y or n please";;
  esac
done

processSettings
editVenvPostScripts
